name: Deploy

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login To Docker Registry
      run: echo "${{ secrets.GIT_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      
    - name: Build Docker Image
      run: |
        IMAGE_ID=$(echo ghcr.io/${{ github.repository_owner }}/boated-fe | tr '[A-Z]' '[a-z]')
        echo IMAGE_ID=$IMAGE_ID
        
        docker build -t $IMAGE_ID:${{github.sha}} -t $IMAGE_ID:latest .
        docker push $IMAGE_ID:${{github.sha}}
        docker push $IMAGE_ID:latest
        
    - name: Deploy To Develop Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.DEPLOY_SERVER_HOST}}
        username: ${{secrets.DEPLOY_USERNAME}}
        password: ${{secrets.DEPLOY_PASSWORD}}
        script: cd boated ; sh boated-fe.sh
